### ISSUE TITLE
reflowable converstion

### ISSUE THREAD

**Issue by mrifni** [dodeeric/pdf2epubEX#1]
is it possible to use converted PDFs from https://www.willus.com/k2pdfopt/ and make reflowable layout epubs ?

**Comment by dodeeric** [comment]
In fact, that tool (k2pdfopt) converts a text PDF to an image PDF. That new PDF is then even more difficult to convert to a reflowable text ePub.

I have tried a free online converter with the three sample PDF files you gave: [online-convert.com](https://ebook.online-convert.com/convert-to-epub).

- Explanation of a Summary of Aqeedat Hamawiyyah: [PDF](http://files.dodeeric.be/Temp/Explanation-of-a-Summary-of-Aqeedat-Hamawiyyah.pdf) | [ePub](http://files.dodeeric.be/Temp/Explanation-of-a-Summary-of-Aqeedat-Hamawiyyah.epub)
- Mystical Poems of Rumi: [PDF](http://files.dodeeric.be/Temp/Mystical-Poems-of-Rumi.pdf) | [ePub](http://files.dodeeric.be/Temp/Mystical-Poems-of-Rumi.epub)
- Java8 in Action: [PDF](http://files.dodeeric.be/Temp/Java8-in-Action.pdf) | [ePub](http://files.dodeeric.be/Temp/Java8-in-Action.epub)

These ePub files need to be edited, for example to remove `<br/>` tags that are cuting sentences by going to a new line.

To edit ePub files, different free sofwares are available like [Calibre](https://calibre-ebook.com/) and [Sigil](https://sigil-ebook.com/).

**Comment by mrifni** [comment]
thank you!

**Comment by dodeeric** [comment]
I am implementing a _reflowable text_ option using _ebook-convert_ command from _Calibre_.
