### ISSUE TITLE
Warning message: pdf2htmlEX: unrecognized option `--dpi'

### ISSUE THREAD

**Issue by yuw** [dodeeric/pdf2epubEX#4]
Isn't the option you give to pdf2htmlEX, not `---dpi` but `---hdpi` and `---vdpi`?

cf. https://github.com/pdf2htmlEX/pdf2htmlEX/wiki/Command-Line-Options

**Comment by dodeeric** [comment]
In the original project (until version 0.14.6, repository [here](https://github.com/coolwanglu/pdf2htmlEX)), --vdpi and --hdpi were used. In the new project (in this repository), it has been replaced by --dpi. The manual page you gave is for version 0.12 (old version).

**Comment by yuw** [comment]
Oh! I see that the options have changed.
I misunderstood because the version of pdf2htmlEX installed on MacOS with homebrew was 0.14.6.
Thank you.
